# Generated by Django 2.2.5 on 2019-09-23 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskIncidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('incident_type', models.CharField(choices=[('soft', 'Программный сбой'), ('zip', 'Расходные материалы'), ('crq', 'Запрос на изменение')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
