# Generated by Django 2.2.5 on 2019-09-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskIncidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('soft', 'Программный сбой'), ('zip', 'Расходные материалы'), ('crq', 'Запрос на изменение')], max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.HelpDeskUsers')),
            ],
        ),
    ]
