# Generated by Django 2.2.5 on 2019-09-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_helpdeskincidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskincidents',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='helpdeskincidents',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
