# Generated by Django 2.2.5 on 2019-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_helpdeskincidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskincidents',
            name='state',
            field=models.CharField(choices=[('new', 'Новый'), ('worked', 'В работе'), ('wait', 'В ожидании'), ('done', 'Выполнена'), ('closed', 'Закрыта')], default='new', editable=False, max_length=100),
        ),
    ]
