# Generated by Django 2.2.5 on 2019-10-08 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191008_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilebasicsettings',
            name='default_service',
            field=models.CharField(choices=[('helpdesk', 'Help Desk'), ('taxi', 'Сервис Такси'), ('main', 'Главная страница')], default='main', max_length=100),
        ),
        migrations.AlterField(
            model_name='profilebasicsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
